#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Patch app.js: add missing CONTENT_T entries for 8 languages (en/zh already in t(), add es/ar/hi/pt/fr/ja)."""
import re, json

# ── 7 extra languages translations (index matches missing_keys.json order) ──
EXTRA = [
  {"es":"NexBids ofrece un ecosistema completo de publicidad programática — DSP, ADX y SSP — para anunciantes, publishers, desarrolladores y agencias.","ar":"تقدم NexBids نظامًا بيئيًا متكاملًا للإعلان البرمجي — DSP وADX وSSP.","hi":"NexBids एक पूर्ण-स्टैक प्रोग्रामेटिक विज्ञापन इकोसिस्टम प्रदान करता है।","pt":"NexBids oferece um ecossistema completo de publicidade programática — DSP, ADX e SSP.","fr":"NexBids offre un écosystème publicitaire programmatique complet — DSP, ADX et SSP.","ja":"NexBidsはフルスタックのプログラマティック広告エコシステムを提供します。"},
  {"es":"<80ms Respuesta de puja","ar":"استجابة مزايدة أقل من 80 مللي ثانية","hi":"<80ms बोली प्रतिक्रिया","pt":"<80ms Resposta de lance","fr":"<80ms Réponse aux enchères","ja":"<80ms 入札レスポンス"},
  {"es":"E-commerce, estudios de juegos, desarrolladores de apps y marcas que buscan adquirir usuarios e impulsar ingresos globalmente.","ar":"التجارة الإلكترونية واستوديوهات الألعاب ومطورو التطبيقات والمسوقون الراغبون في اكتساب المستخدمين وزيادة الإيرادات عالميًا.","hi":"ई-कॉमर्स, गेमिंग स्टूडियो, ऐप डेवलपर्स और ब्रांड मार्केटर्स जो वैश्विक स्तर पर यूजर्स हासिल करना चाहते हैं।","pt":"E-commerce, estúdios de jogos, desenvolvedores de apps e marcas buscando adquirir usuários e aumentar receitas globalmente.","fr":"E-commerce, studios de jeux, développeurs d'apps et marques cherchant à acquérir des utilisateurs mondialement.","ja":"Eコマース、ゲームスタジオ、アプリ開発者がグローバルにユーザー獲得と収益成長を目指します。"},
  {"es":"Propietarios de sitios web, desarrolladores de apps, estudios de juegos y empresas de medios digitales que buscan maximizar ingresos publicitarios.","ar":"أصحاب المواقع ومطورو تطبيقات الجوال واستوديوهات الألعاب وشركات الإعلام الرقمي الساعون إلى تعظيم إيرادات الإعلانات.","hi":"वेबसाइट मालिक, मोबाइल ऐप डेवलपर्स, गेम स्टूडियो और डिजिटल मीडिया कंपनियां।","pt":"Proprietários de sites, desenvolvedores de apps, estúdios de jogos e empresas de mídia digital.","fr":"Propriétaires de sites, développeurs d'apps, studios de jeux et entreprises de médias numériques.","ja":"ウェブサイトオーナー、モバイルアプリ開発者、ゲームスタジオ、デジタルメディア企業。"},
  {"es":"Agencias de servicio completo y rendimiento que gestionan campañas programáticas para múltiples clientes anunciantes en todo el mundo.","ar":"وكالات الخدمة الكاملة والأداء التي تدير الحملات البرمجية لعملاء معلنين متعددين حول العالم.","hi":"प्रदर्शन और पूर्ण-सेवा एजेंसियां जो दुनिया भर में कई विज्ञापनदाताओं के लिए अभियान प्रबंधित करती हैं।","pt":"Agências de serviço completo e de performance que gerenciam campanhas programáticas para múltiplos clientes no mundo todo.","fr":"Agences de service complet et de performance gérant des campagnes programmatiques pour de nombreux clients dans le monde.","ja":"世界中の複数の広告主向けにプログラマティックキャンペーンを管理するエージェンシー。"},
  {"es":"Nuestra infraestructura propietaria de IA/ML procesa 50 mil millones de solicitudes de puja diariamente en menos de 100 milisegundos.","ar":"تعالج بنيتنا التحتية الخاصة للذكاء الاصطناعي 50 مليار طلب مزايدة يوميًا في أقل من 100 مللي ثانية.","hi":"हमारा AI/ML इन्फ्रास्ट्रक्चर प्रतिदिन 500 बिलियन बिड अनुरोध 100ms से कम में प्रोसेस करता है।","pt":"Nossa infraestrutura de IA/ML processa 50 bilhões de solicitações de lance diariamente em menos de 100 milissegundos.","fr":"Notre infrastructure IA/ML traite 50 milliards de demandes d'enchères par jour en moins de 100 millisecondes.","ja":"独自のAI/MLインフラが毎日500億件の入札リクエストを100ms以内に処理します。"},
  {"es":"Ya sea anunciante buscando alcance global, publisher maximizando ingresos o agencia — NexBids tiene la solución.","ar":"سواء كنت معلنًا أو ناشرًا أو وكالة — NexBids لديه الحل.","hi":"चाहे आप विज्ञापनदाता हों, प्रकाशक हों, या एजेंसी — NexBids के पास समाधान है।","pt":"Seja anunciante, publisher ou agência — NexBids tem a solução.","fr":"Que vous soyez annonceur, éditeur ou agence — NexBids a la solution.","ja":"広告主、パブリッシャー、エージェンシーのいずれでも — NexBidsに解決策があります。"},
  {"es":"NexBids DSP brinda herramientas de IA para llegar a las audiencias correctas en 150+ países y dominar cada canal digital.","ar":"يمنح NexBids DSP المعلنين أدوات ذكاء اصطناعي للوصول إلى الجماهير المناسبة عبر 150+ دولة.","hi":"NexBids DSP विज्ञापनदाताओं को 150+ देशों में सही दर्शकों तक पहुंचने के लिए AI टूल देता है।","pt":"NexBids DSP fornece ferramentas de IA para alcançar o público certo em 150+ países.","fr":"NexBids DSP donne aux annonceurs des outils IA pour atteindre les bonnes audiences dans 150+ pays.","ja":"NexBids DSPは広告主に150カ国以上で適切なオーディエンスへリーチするAIツールを提供します。"},
  {"es":"Todo lo que necesitas para ganar en programática","ar":"كل ما تحتاجه للفوز في الإعلان البرمجي","hi":"प्रोग्रामेटिक में जीतने के लिए जो कुछ भी चाहिए","pt":"Tudo que você precisa para vencer no programático","fr":"Tout ce dont vous avez besoin pour gagner en programmatique","ja":"プログラマティックで勝つために必要なすべて"},
  {"es":"NexBids SSP conecta tu inventario con 50.000+ anunciantes premium en todo el mundo mediante header bidding y optimización de floor con IA.","ar":"يربط NexBids SSP مخزونك بأكثر من 50,000 معلن متميز حول العالم.","hi":"NexBids SSP आपकी इन्वेंटरी को दुनिया भर के 50,000+ प्रीमियम विज्ञापनदाताओं से जोड़ता है।","pt":"NexBids SSP conecta seu inventário a 50.000+ anunciantes premium mundialmente.","fr":"NexBids SSP connecte votre inventaire à 50 000+ annonceurs premium dans le monde.","ja":"NexBids SSPはあなたのインベントリを世界中の50,000以上のプレミアム広告主に接続します。"},
  {"es":"NexBids Agency Solutions da a las agencias las herramientas, precios y soporte para ganar más clientes y entregar resultados programáticos excepcionales.","ar":"يمنح NexBids Agency Solutions الوكالات الأدوات والأسعار والدعم لكسب المزيد من العملاء.","hi":"NexBids Agency Solutions एजेंसियों को अधिक क्लाइंट जीतने के लिए टूल, प्राइसिंग और सपोर्ट देता है।","pt":"NexBids Agency Solutions dá às agências as ferramentas, preços e suporte para conquistar mais clientes.","fr":"NexBids Agency Solutions donne aux agences les outils, les prix et le support pour gagner plus de clients.","ja":"NexBidsエージェンシーソリューションは更多くのクライアントを獲得するためのツール・価格・サポートを提供します。"},
  {"es":"La infraestructura programática completa de NexBids — DSP, ADX y SSP — trabaja perfectamente junta para impulsar el mercado de publicidad digital.","ar":"تعمل البنية التحتية البرمجية الكاملة لـ NexBids معًا بسلاسة لتشغيل سوق الإعلانات الرقمية.","hi":"NexBids का फुल-स्टैक इन्फ्रास्ट्रक्चर डिजिटल विज्ञापन मार्केटप्लेस के हर पहलू को शक्ति देता है।","pt":"A infraestrutura completa da NexBids trabalha em conjunto para impulsionar o mercado de publicidade digital.","fr":"L'infrastructure complète de NexBids fonctionne parfaitement ensemble pour alimenter le marché publicitaire numérique.","ja":"NexBidsのフルスタックインフラがデジタル広告マーケットプレイスのあらゆる側面を支えます。"},
  {"es":"La DSP impulsada por IA para el rendimiento. Alcanza audiencias en 150+ países, optimiza KPIs en tiempo real y escala con confianza.","ar":"منصة جانب الطلب المدعومة بالذكاء الاصطناعي للأداء. تصل إلى الجماهير عبر 150+ دولة.","hi":"परफॉर्मेंस के लिए AI-संचालित DSP। 150+ देशों में सही दर्शकों तक पहुंचें।","pt":"A DSP alimentada por IA para performance. Alcance o público certo em 150+ países.","fr":"La DSP alimentée par l'IA pour la performance. Atteignez les bonnes audiences dans 150+ pays.","ja":"パフォーマンスのためのAI搭載DSP。150カ国以上で適切なオーディエンスへリーチします。"},
  {"es":"El exchange de anuncios neutral y de alto rendimiento que procesa 50 mil millones de subastas diariamente con latencia inferior a 100ms.","ar":"بورصة الإعلانات المحايدة عالية الأداء التي تعالج 50 مليار مزاد يوميًا بأقل من 100 مللي ثانية.","hi":"उच्च-प्रदर्शन, तटस्थ एड एक्सचेंज जो 100ms से कम लेटेंसी के साथ प्रतिदिन 500 बिलियन नीलामी प्रोसेस करता है।","pt":"O exchange neutro e de alto desempenho processando 50 bilhões de leilões diariamente com latência abaixo de 100ms.","fr":"L'exchange publicitaire neutre et haute performance traitant 50 milliards d'enchères par jour en moins de 100ms.","ja":"毎日500億件のオークションを100ms以下のレイテンシで処理する高性能・中立的な広告エクスチェンジ。"},
  {"es":"La SSP inteligente que maximiza los ingresos del publisher mediante header bidding, optimización de rendimiento con IA e integración de SDK.","ar":"منصة جانب العرض الذكية التي تعظم إيرادات الناشر من خلال header bidding وتحسين العائد بالذكاء الاصطناعي.","hi":"इंटेलिजेंट SSP जो हेडर बिडिंग और AI यील्ड ऑप्टिमाइजेशन के जरिए प्रकाशक राजस्व को अधिकतम करता है।","pt":"A SSP inteligente que maximiza a receita do publisher por header bidding e otimização de yield com IA.","fr":"La SSP intelligente qui maximise les revenus des éditeurs via header bidding et optimisation du rendement par IA.","ja":"ヘッダービディングとAI収益最適化でパブリッシャー収益を最大化するインテリジェントSSP。"},
  {"es":"NexBids está diseñado desde cero para velocidad, inteligencia y escala global. Nuestra pila tecnológica procesa billones de señales de datos diariamente.","ar":"صُمِّم NexBids من الصفر للسرعة والذكاء والحجم العالمي. تعالج تقنياتنا تريليونات إشارات البيانات يوميًا.","hi":"NexBids को गति, बुद्धिमत्ता और वैश्विक स्केल के लिए डिज़ाइन किया गया है। हमारा टेक स्टैक प्रतिदिन खरबों डेटा सिग्नल प्रोसेस करता है।","pt":"NexBids é projetado do zero para velocidade, inteligência e escala global. Nossa pilha tecnológica processa trilhões de sinais de dados diariamente.","fr":"NexBids est conçu depuis le début pour la vitesse, l'intelligence et l'échelle mondiale. Notre pile technologique traite des billions de signaux de données quotidiennement.","ja":"NexBidsはスピード、インテリジェンス、グローバルスケールのために一から設計されています。"},
  {"es":"Nuestra plataforma de IA procesa billones de señales de subasta históricas para impulsar la optimización en tiempo real en la publicidad programática.","ar":"تعالج منصتنا للذكاء الاصطناعي تريليونات من إشارات المزاد التاريخية للتحسين الفوري.","hi":"हमारा AI प्लेटफॉर्म रियल-टाइम ऑप्टिमाइजेशन के लिए खरबों ऐतिहासिक नीलामी सिग्नल प्रोसेस करता है।","pt":"Nossa plataforma de IA processa trilhões de sinais de leilão históricos para otimização em tempo real.","fr":"Notre plateforme IA traite des billions de signaux d'enchères historiques pour l'optimisation en temps réel.","ja":"私たちのAIプラットフォームはリアルタイム最適化のために数兆の過去のオークションシグナルを処理します。"},
  {"es":"Descubre cómo marcas globales, desarrolladores de apps, publishers y agencias usan NexBids para impulsar un crecimiento medible y sostenible.","ar":"اكتشف كيف تستخدم العلامات التجارية العالمية ومطورو التطبيقات والناشرون NexBids لتحقيق نمو مستدام.","hi":"जानें कि वैश्विक ब्रांड, ऐप डेवलपर्स, प्रकाशक और एजेंसियां NexBids का उपयोग कैसे करती हैं।","pt":"Descubra como marcas globais, desenvolvedores de apps, publishers e agências usam NexBids para crescimento mensurável.","fr":"Découvrez comment les marques mondiales, développeurs d'apps, éditeurs et agences utilisent NexBids.","ja":"グローバルブランド、アプリ開発者、パブリッシャー、エージェンシーがNexBidsをどのように活用するか。"},
  {"es":"Desde marcas globales de e-commerce que escalan a nuevos mercados hasta estudios de juegos móviles — NexBids impulsa el rendimiento en cada etapa.","ar":"من العلامات التجارية للتجارة الإلكترونية إلى استوديوهات الألعاب — NexBids يدفع الأداء في كل مرحلة.","hi":"वैश्विक ई-कॉमर्स ब्रांडों से मोबाइल गेमिंग स्टूडियो तक — NexBids विकास के हर चरण में परफॉर्मेंस को शक्ति देता है।","pt":"De marcas globais de e-commerce a estúdios de jogos móveis — NexBids impulsiona performance em cada etapa.","fr":"Des marques mondiales d'e-commerce aux studios de jeux mobiles — NexBids propulse la performance à chaque étape.","ja":"グローバルEコマースブランドからモバイルゲームスタジオまで、NexBidsは成長のあらゆる段階を支えます。"},
  {"es":"Una marca de moda e-commerce global de rápido crecimiento en 12 países transformó el programático en su motor de ingresos de más rápido crecimiento.","ar":"حوّلت علامة تجارية للأزياء الإلكترونية تعمل في 12 دولة الإعلان البرمجي إلى محركها الأسرع نموًا.","hi":"12 देशों में काम करने वाले एक वैश्विक फैशन ई-कॉमर्स ब्रांड ने प्रोग्रामेटिक को अपना सबसे तेज़ राजस्व चालक बना दिया।","pt":"Uma marca global de moda e-commerce em 12 países transformou o programático em seu motor de receita de crescimento mais rápido.","fr":"Une marque mondiale de mode e-commerce dans 12 pays a transformé le programmatique en son moteur de revenus à la croissance la plus rapide.","ja":"12カ国で展開するグローバルファッションEコマースブランドがプログラマティックを最急成長収益ドライバーに変えました。"},
  {"es":"\"NexBids transformó el programático de un canal descartado en nuestro motor de ingresos de mayor crecimiento. El ROAS logrado superó todo lo que creíamos posible.\"","ar":"\"حوّل NexBids الإعلان البرمجي من قناة كنا قد تخلينا عنها إلى محرك إيراداتنا الأسرع نموًا.\"","hi":"\"NexBids ने प्रोग्रामेटिक को छोड़े गए चैनल से सबसे तेज़ बढ़ते राजस्व चालक में बदल दिया।\"","pt":"\"NexBids transformou o programático de um canal descartado no nosso motor de receita de maior crescimento.\"","fr":"\"NexBids a transformé le programmatique d'un canal abandonné en notre moteur de revenus à la plus forte croissance.\"","ja":"\"NexBidsはプログラマティックを諦めていたチャネルから最も急成長する収益ドライバーへと変革しました。\""},
  {"es":"Un estudio de RPG móvil top necesitaba escalar más allá de sus canales existentes sin sacrificar la calidad de los jugadores.","ar":"احتاج استوديو RPG للجوال إلى التوسع إلى ما بعد قنواته الحالية دون التضحية بجودة اللاعبين.","hi":"एक टॉप-ग्रॉसिंग मोबाइल RPG स्टूडियो को खिलाड़ी की गुणवत्ता का बलिदान किए बिना स्केल करने की जरूरत थी।","pt":"Um estúdio de RPG móvel dos mais rentáveis precisava escalar sem sacrificar a qualidade dos jogadores.","fr":"Un studio de RPG mobile top devait se développer sans sacrifier la qualité des joueurs.","ja":"トップ収益モバイルRPGスタジオがプレイヤー品質を犠牲にせずにスケールする必要がありました。"},
  {"es":"\"Probamos todos los DSP principales y ninguno igualó la calidad de jugadores de NexBids. Su LTV Optimizer lo cambió todo — ahora somos rentables D180 en todos los mercados.\"","ar":"\"جربنا كل DSP رئيسي ولم يستطع أحد مضاهاة جودة لاعبي NexBids. غيّر LTV Optimizer كل شيء.\"","hi":"\"हमने हर DSP आजमाया, कोई भी NexBids की खिलाड़ी गुणवत्ता से मेल नहीं खाया। LTV Optimizer ने सब बदल दिया।\"","pt":"\"Experimentamos todos os DSPs e nenhum igualou a qualidade dos jogadores do NexBids. O LTV Optimizer mudou tudo.\"","fr":"\"Nous avons testé tous les DSP et aucun n'a égalé la qualité des joueurs de NexBids. Le LTV Optimizer a tout changé.\"","ja":"\"主要なDSPをすべて試しましたがNexBidsのプレイヤー品質に匹敵するものはありませんでした。LTV Optimizerがすべてを変えました。\""},
  {"es":"Una app de productividad necesitaba un socio programático para expandirse de 3 a 28 mercados globales manteniendo los objetivos de CPA.","ar":"احتاج تطبيق الإنتاجية إلى شريك برمجي للتوسع من 3 إلى 28 سوقًا مع الحفاظ على أهداف CPA.","hi":"एक प्रोडक्टिविटी ऐप को CPA लक्ष्य बनाए रखते हुए 3 से 28 बाजारों में विस्तार के लिए पार्टनर की जरूरत थी।","pt":"Um app de produtividade precisava de parceiro programático para expandir de 3 para 28 mercados mantendo metas de CPA.","fr":"Une app de productivité avait besoin d'un partenaire programmatique pour s'étendre de 3 à 28 marchés tout en maintenant les objectifs de CPA.","ja":"生産性アプリがCPAターゲットを維持しながら3市場から28市場に拡大するプログラマティックパートナーを必要としていました。"},
  {"es":"Desde sitios de noticias independientes hasta estudios de juegos móviles — descubre cómo los publishers desbloquean su verdadero potencial de ingresos con NexBids SSP.","ar":"من مواقع الأخبار إلى استوديوهات الألعاب — اكتشف كيف يطلق الناشرون إمكاناتهم الإيرادية مع NexBids SSP.","hi":"स्वतंत्र समाचार साइटों से मोबाइल गेम स्टूडियो तक — NexBids SSP के साथ राजस्व क्षमता अनलॉक करें।","pt":"De sites de notícias independentes a estúdios de jogos móveis — desbloqueie o potencial de receita com NexBids SSP.","fr":"Des sites d'actualités aux studios de jeux mobiles — débloquent leur vrai potentiel de revenus avec NexBids SSP.","ja":"独立ニュースサイトからモバイルゲームスタジオまでNexBids SSPで真の収益ポテンシャルを解放します。"},
  {"es":"Una plataforma líder de noticias financieras regionales migró al header bidding de NexBids, transformando sus ingresos publicitarios en 90 días.","ar":"انتقلت منصة أخبار مالية إقليمية رائدة إلى NexBids header bidding وحوّلت أداء إيراداتها في 90 يومًا.","hi":"एक प्रमुख क्षेत्रीय वित्त समाचार प्लेटफॉर्म NexBids हेडर बिडिंग में माइग्रेट हुआ और 90 दिनों में राजस्व परिवर्तन हासिल किया।","pt":"Uma plataforma líder de notícias financeiras regionais migrou para o header bidding da NexBids, transformando receitas em 90 dias.","fr":"Une plateforme leader d'actualités financières régionales a migré vers le header bidding NexBids, transformant ses revenus en 90 jours.","ja":"大手地域金融ニュースプラットフォームがNexBidsヘッダービディングに移行し、90日で収益を変革しました。"},
  {"es":"\"La implementación de header bidding de NexBids fue transformadora. En 90 días nuestros CPMs subieron 67% y los ingresos mensuales crecieron $200K.\"","ar":"\"كان تطبيق header bidding من NexBids تحويليًا. في 90 يومًا، ارتفعت CPMs 67% ونمت الإيرادات بـ200,000 دولار.\"","hi":"\"NexBids का हेडर बिडिंग परिवर्तनकारी था। 90 दिनों में CPM 67% बढ़े और मासिक राजस्व $200K बढ़ा।\"","pt":"\"A implementação de header bidding da NexBids foi transformadora. Em 90 dias nossos CPMs subiram 67% e a receita mensal cresceu $200K.\"","fr":"\"La mise en œuvre du header bidding de NexBids a été transformatrice. En 90 jours nos CPMs ont augmenté de 67% et les revenus mensuels ont crû de 200 000$.\"","ja":"\"NexBidsのヘッダービディング実装は変革的でした。90日でCPMが67%上昇し、月次収益が20万ドル増加しました。\""},
  {"es":"Un popular app de lifestyle con más de 8M de MAU solo monetizaba con banners. NexBids SSP desbloqueó video recompensado e intersticiales, triplicando los ingresos mensuales.","ar":"كان تطبيق نمط حياة مع 8 ملايين مستخدم يحقق الدخل فقط من البانر. أطلق NexBids SSP الفيديو المكافأ والإعلانات البينية.","hi":"8M+ MAU वाला एक लाइफस्टाइल ऐप केवल बैनर से मोनेटाइज हो रहा था। NexBids SSP ने रिवॉर्डेड वीडियो अनलॉक किया।","pt":"Um app de lifestyle com mais de 8M de MAU só monetizava com banners. NexBids SSP desbloqueou vídeo recompensado e intersticiais.","fr":"Une app de lifestyle avec plus de 8M de MAU ne monétisait qu'avec des bannières. NexBids SSP a débloqué la vidéo récompensée.","ja":"800万MAUのライフスタイルアプリがバナーのみで収益化していました。NexBids SSPがリワード動画を解放しました。"},
  {"es":"\"Éramos escépticos sobre el video recompensado — NexBids nos demostró estar equivocados. Los ingresos se triplicaron y la retención mejoró.\"","ar":"\"كنا متشككين في الفيديو المكافأ — NexBids أثبت أننا مخطئون. تضاعفت الإيرادات ثلاث مرات وتحسن الاحتفاظ.\"","hi":"\"रिवॉर्डेड वीडियो को लेकर संशय था — NexBids ने गलत साबित किया। राजस्व तीन गुना हुआ और रिटेंशन बेहतर हुई।\"","pt":"\"Éramos céticos sobre o vídeo recompensado — NexBids provou que estávamos errados. A receita triplicou e a retenção melhorou.\"","fr":"\"Nous étions sceptiques sur la vidéo récompensée — NexBids a prouvé que nous avions tort. Les revenus ont triplé et la rétention s'est améliorée.\"","ja":"\"リワード動画に懐疑的でしたがNexBidsが間違いを証明しました。収益は3倍になりリテンションも改善しました。\""},
  {"es":"Un estudio de juegos móviles casuales con más de 15M de descargas integró NexBids SSP y logró un aumento de ingresos del 145%.","ar":"دمج استوديو ألعاب الجوال العرضية مع 15 مليون تنزيل NexBids SSP وحقق زيادة في الإيرادات بنسبة 145%.","hi":"15M+ डाउनलोड वाले एक कैजुअल गेम स्टूडियो ने NexBids SSP इंटीग्रेट किया और 145% राजस्व वृद्धि हासिल की।","pt":"Um estúdio de jogos casuais com mais de 15M de downloads integrou NexBids SSP e obteve 145% de aumento de receita.","fr":"Un studio de jeux casuales avec plus de 15M de téléchargements a intégré NexBids SSP et obtenu une hausse de revenus de 145%.","ja":"1500万以上のダウンロードを持つカジュアルゲームスタジオがNexBids SSPで145%の収益増を達成しました。"},
  {"es":"La Empresa Detrás de la Infraestructura Programática Mundial","ar":"الشركة وراء البنية التحتية البرمجية العالمية","hi":"दुनिया के प्रोग्रामेटिक इन्फ्रास्ट्रक्चर के पीछे की कंपनी","pt":"A Empresa por Trás da Infraestrutura Programática Mundial","fr":"L'Entreprise Derrière l'Infrastructure Programmatique Mondiale","ja":"世界のプログラマティックインフラを支える会社"},
  {"es":"De una visión fundacional audaz en 2018 a un líder global de ad tech sirviendo 150+ países — conoce al equipo, la misión y los valores de NexBids.","ar":"من رؤية تأسيسية جريئة عام 2018 إلى قائد عالمي في تقنية الإعلانات يخدم 150+ دولة.","hi":"2018 में एक साहसी दृष्टि से 150+ देशों की सेवा करने वाले वैश्विक एड टेक लीडर तक।","pt":"De uma visão fundacional ousada em 2018 a um líder global de ad tech servindo 150+ países.","fr":"D'une vision fondatrice audacieuse en 2018 à un leader mondial de l'ad tech servant 150+ pays.","ja":"2018年の大胆な創業ビジョンから150カ国以上を支えるグローバルなアドテクリーダーへ。"},
  {"es":"De un pequeño equipo con una gran idea a una empresa global de ad tech sirviendo a miles de anunciantes, publishers y agencias en 150+ países.","ar":"من فريق صغير بفكرة كبيرة إلى شركة عالمية لتقنية الإعلانات تخدم آلاف المعلنين والناشرين في 150+ دولة.","hi":"एक बड़े विचार वाली छोटी टीम से 150+ देशों में हजारों की सेवा करने वाली वैश्विक एड टेक कंपनी तक।","pt":"De uma pequena equipe com uma grande ideia a uma empresa global de ad tech servindo milhares em 150+ países.","fr":"D'une petite équipe avec une grande idée à une entreprise mondiale d'ad tech servant des milliers dans 150+ pays.","ja":"大きなアイデアの小さなチームから150カ国以上の何千もの顧客にサービスを提供するグローバルなアドテク企業へ。"},
  {"es":"NexBids fue fundada en 2018 por veteranos de la tecnología publicitaria. Vieron de primera mano cómo la publicidad programática seguía siendo innecesariamente compleja para la mayoría.","ar":"تأسست NexBids عام 2018 على يد خبراء في تقنية الإعلانات رأوا كيف ظل الإعلان البرمجي معقدًا بلا داعٍ.","hi":"NexBids की स्थापना 2018 में विज्ञापन प्रौद्योगिकी के अनुभवी लोगों ने की। उन्होंने देखा कि प्रोग्रामेटिक विज्ञापन अनावश्यक रूप से जटिल रहा।","pt":"NexBids foi fundada em 2018 por veteranos em tecnologia de publicidade que viram como a publicidade programática permanecia desnecessariamente complexa.","fr":"NexBids a été fondée en 2018 par des vétérans de la technologie publicitaire qui ont vu comment la publicité programmatique restait inutilement complexe.","ja":"NexBidsは2018年に広告テクノロジーのベテランたちによって設立されました。プログラマティック広告が不必要に複雑であることを目の当たりにしていました。"},
  {"es":"La visión fundacional: construir una plataforma programática completa que combinara sofisticación tecnológica con accesibilidad y transparencia.","ar":"الرؤية التأسيسية: بناء منصة برمجية متكاملة تجمع التطور التكنولوجي مع سهولة الوصول والشفافية.","hi":"संस्थापन दृष्टि: तकनीकी परिष्कार को पहुंच और पारदर्शिता के साथ जोड़ने वाला फुल-स्टैक प्लेटफॉर्म बनाना।","pt":"A visão fundacional: construir uma plataforma programática completa que combinasse sofisticação tecnológica com acessibilidade e transparência.","fr":"La vision fondatrice: construire une plateforme programmatique complète combinant sophistication technologique, accessibilité et transparence.","ja":"創業ビジョン：技術的洗練さとアクセシビリティ・透明性を組み合わせたフルスタックプログラマティックプラットフォームの構築。"},
  {"es":"Democratizar el acceso a la mejor tecnología de publicidad programática — para que cada anunciante, publisher y agencia pueda competir y crecer.","ar":"إضفاء الطابع الديمقراطي على الوصول إلى أفضل تقنية إعلانية برمجية لكل معلن وناشر ووكالة.","hi":"दुनिया की सर्वश्रेष्ठ प्रोग्रामेटिक विज्ञापन तकनीक तक पहुंच को लोकतांत्रिक बनाना।","pt":"Democratizar o acesso à melhor tecnologia de publicidade programática para que cada anunciante, publisher e agência possa competir e crescer.","fr":"Démocratiser l'accès à la meilleure technologie de publicité programmatique pour que chaque annonceur, éditeur et agence puisse concourir et grandir.","ja":"世界最高のプログラマティック広告テクノロジーへのアクセスを民主化する。"},
  {"es":"Un ecosistema de publicidad digital inteligente, transparente, eficiente y respetuoso de la privacidad para todos los participantes.","ar":"نظام بيئي للإعلان الرقمي ذكي وشفاف وفعال ومحترم للخصوصية لجميع المشاركين.","hi":"सभी प्रतिभागियों के लिए बुद्धिमान, पारदर्शी, कुशल और गोपनीयता का सम्मान करने वाला डिजिटल विज्ञापन इकोसिस्टम।","pt":"Um ecossistema de publicidade digital inteligente, transparente, eficiente e respeitoso da privacidade para todos os participantes.","fr":"Un écosystème publicitaire numérique intelligent, transparent, efficace et respectueux de la vie privée pour tous les participants.","ja":"すべての参加者のためのインテリジェントで透明、効率的でプライバシーを尊重するデジタル広告エコシステム。"},
  {"es":"En NexBids, nuestra misión es hacer la publicidad programática más inteligente, rápida y accesible para todos.","ar":"في NexBids، مهمتنا هي جعل الإعلان البرمجي أكثر ذكاءً وسرعة وسهولة للجميع.","hi":"NexBids में हमारा मिशन प्रोग्रामेटिक विज्ञापन को सभी के लिए स्मार्ट, तेज और अधिक सुलभ बनाना है।","pt":"Na NexBids, nossa missão é tornar a publicidade programática mais inteligente, rápida e acessível para todos.","fr":"Chez NexBids, notre mission est de rendre la publicité programmatique plus intelligente, plus rapide et plus accessible pour tous.","ja":"NexBidsでは、プログラマティック広告をすべての人にとってよりスマートで速く、アクセスしやすくすることが使命です。"},
  {"es":"Acepto los","ar":"أوافق على","hi":"मैं सहमत हूं","pt":"Concordo com os","fr":"J'accepte les","ja":"同意します"},
  {"es":"Lo sentimos, la página no existe o no está disponible temporalmente. Puede deberse a un problema de red.","ar":"عذرًا، الصفحة غير موجودة أو غير متاحة مؤقتًا. قد يكون بسبب مشكلة في الشبكة.","hi":"क्षमा करें, यह पृष्ठ मौजूद नहीं है या अस्थायी रूप से अनुपलब्ध है।","pt":"Desculpe, a página não existe ou está temporariamente indisponível. Pode ser devido a um problema de rede.","fr":"Désolé, la page n'existe pas ou est temporairement indisponible. Cela peut être dû à un problème réseau.","ja":"申し訳ありませんが、ページが存在しないか一時的に利用できません。"},
]

def esc(s):
    return s.replace("\\", "\\\\").replace("'", "\\'")

with open('missing_keys.json', encoding='utf-8') as f:
    missing = json.load(f)

with open('app.js', encoding='utf-8') as f:
    src = f.read()

ct_start = src.find('const CONTENT_T = {')
ct_end   = src.find('\n};', ct_start) + 2

lines = []
for i, item in enumerate(missing):
    en_key = item['en']
    zh_val = item['zh']
    extra  = EXTRA[i] if i < len(EXTRA) else {}
    lines.append(f"  '{esc(en_key)}': {{")
    lines.append(f"    zh: '{esc(zh_val)}',")
    for lang in ['es','ar','hi','pt','fr','ja']:
        v = extra.get(lang, zh_val)
        lines.append(f"    {lang}: '{esc(v)}',")
    lines.append(f"  }},")

block = '\n'.join(lines) + '\n'
new_src = src[:ct_end-1] + block + src[ct_end-1:]

with open('app.js', 'w', encoding='utf-8') as f:
    f.write(new_src)

print(f"Inserted {len(missing)} entries into CONTENT_T.")
